name: flutter_form_builder
description: This package helps in creation of forms in Flutter by removing the boilerplate code, reusing validation, react to changes, and collect final user input.
version: 4.0.2
homepage: https://github.com/danvick/flutter_form_builder

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  community_material_icon: ^5.4.55
  country_pickers: ^1.3.0
  date_range_picker: ^1.0.6
  datetime_picker_formfield: ^1.0.0
  dropdown_search: ^0.4.8
  file_picker: ^2.1.0
  flutter_colorpicker: ^0.3.4
  flutter_chips_input:
    git: 
      url: https://github.com/rettechnologys/flutter_chips_input.git
      ref: master
  flutter_datetime_picker: ^1.4.0
  flutter_touch_spin: ^1.0.1
  flutter_typeahead: ^1.9.1
  image_picker: ^0.6.7+14
  image_picker_for_web: ^0.1.0+2
  intl: ^0.16.1
  permission_handler: ^5.0.1+1
  phone_number: ^0.8.1
  rating_bar: ^0.2.0
  signature: ^3.2.0
  validators: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter pub pub run intl_translation:extract_to_arb --output-dir=lib/l10n lib/localization/form_builder_localizations.dart
  # flutter pub pub run intl_translation:generate_from_arb --output-dir=lib/l10n --no-use-deferred-loading lib/localization/form_builder_localizations.dart lib/l10n/intl_*.arb
  intl_translation: ^0.17.10+1
  pedantic: ^1.9.2

flutter:
